# Общие настройки для всех office-хостов (не зависят от исходной ОС)
# OS-специфичные настройки (RemoteForward, TERM) — в darwin/ и linux/

Host office
  User danil
  Hostname 192.168.88.10

Host office2
  User danil
  Hostname 192.168.88.12

Host office3
  User danil

Host office.brandymint.ru
  User danil
