# alias less=$PAGER
alias office="ssh office.brandymint.ru"
alias h='helmfile --skip-deps --no-color'
alias vi='nvim'
alias zz='open -a Zed .'
alias vim-norc='vim -u NORC'
alias vim-none='vim -u NONE'
alias nvim-norc='nvim -u NORC'
alias nvim-none='nvim -u NONE'
alias vim='nvim'
