Host office
  Hostname office.brandymint.ru
  RemoteForward /run/user/1000/gnupg/S.gpg-agent /Users/danil/.gnupg/S.gpg-agent.extra

Host office2
  Hostname office.brandymint.ru
  Port 222
  RemoteForward /run/user/1000/gnupg/S.gpg-agent /Users/danil/.gnupg/S.gpg-agent.extra

Host office3
  Hostname office.brandymint.ru
  Port 223
  RemoteForward /run/user/1000/gnupg/S.gpg-agent /Users/danil/.gnupg/S.gpg-agent.extra
